# yaml-language-server: $schema=https://raw.githubusercontent.com/amnweb/yasb/main/schema.json
watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "none"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 4
      left: 6
      bottom: 4
      right: 6
    widgets:
      left:
        - "power_menu"
        - "komorebi_workspaces"
        - "komorebi_active_layout"
      center:
        - "active_window"
      right:
        - "volume"
        - "clock"

widgets:
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf015"
      uptime: false
      show_user: false
      blur: false
      blur_background: true
      animation_duration: 200
      button_row: 3
      buttons:
        restart:  ["\uead2", "Restart"]
        shutdown: ["\uf011", "Shut Down"]
        lock:     ["\uea75", "Lock"]
        signout:  ["\udb80\udf43", "Sign out"]
        cancel:   ["\udb81\udf3a", "Cancel"]

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\u000d"
      label_workspace_active_btn: "\u000d"
      label_workspace_populated_btn: "\u000d"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        ["bsp", "columns", "rows", "grid", "vertical_stack",
         "horizontal_stack", "ultrawide_vertical_stack", "right_main_vertical_stack"]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximized: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}']"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 60
      max_length_ellipsis: "..."
      monitor_exclusive: true

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar:
        blur: false
        round_corners: true
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
